/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedDeseosRouteImport } from './routes/_authenticated/deseos'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedDiversionRouteImport } from './routes/_authenticated/diversion'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedNotasIndexRouteImport } from './routes/_authenticated/notas.index'
import { Route as AuthenticatedNotasIdRouteImport } from './routes/_authenticated/notas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeseosRoute = AuthenticatedDeseosRouteImport.update({
  id: '/deseos',
  path: '/deseos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiversionRoute = AuthenticatedDiversionRouteImport.update({
  id: '/diversion',
  path: '/diversion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasIndexRoute = AuthenticatedNotasIndexRouteImport.update({
  id: '/notas/',
  path: '/notas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasIdRoute = AuthenticatedNotasIdRouteImport.update({
  id: '/notas/$id',
  path: '/notas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deseos': typeof AuthenticatedDeseosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/diversion': typeof AuthenticatedDiversionRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/notas/': typeof AuthenticatedNotasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deseos': typeof AuthenticatedDeseosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/diversion': typeof AuthenticatedDiversionRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/notas': typeof AuthenticatedNotasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/deseos': typeof AuthenticatedDeseosRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/diversion': typeof AuthenticatedDiversionRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/notas/$id': typeof AuthenticatedNotasIdRoute
  '/_authenticated/notas/': typeof AuthenticatedNotasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/deseos'
    | '/diario'
    | '/diversion'
    | '/galeria'
    | '/panel'
    | '/videos'
    | '/notas/$id'
    | '/notas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/deseos'
    | '/diario'
    | '/diversion'
    | '/galeria'
    | '/panel'
    | '/videos'
    | '/notas/$id'
    | '/notas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/calendario'
    | '/_authenticated/deseos'
    | '/_authenticated/diario'
    | '/_authenticated/diversion'
    | '/_authenticated/galeria'
    | '/_authenticated/panel'
    | '/_authenticated/videos'
    | '/_authenticated/notas/$id'
    | '/_authenticated/notas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deseos': {
      id: '/_authenticated/deseos'
      path: '/deseos'
      fullPath: '/deseos'
      preLoaderRoute: typeof AuthenticatedDeseosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diversion': {
      id: '/_authenticated/diversion'
      path: '/diversion'
      fullPath: '/diversion'
      preLoaderRoute: typeof AuthenticatedDiversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/': {
      id: '/_authenticated/notas/'
      path: '/notas'
      fullPath: '/notas/'
      preLoaderRoute: typeof AuthenticatedNotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/$id': {
      id: '/_authenticated/notas/$id'
      path: '/notas/$id'
      fullPath: '/notas/$id'
      preLoaderRoute: typeof AuthenticatedNotasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDeseosRoute: typeof AuthenticatedDeseosRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedDiversionRoute: typeof AuthenticatedDiversionRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedNotasIdRoute: typeof AuthenticatedNotasIdRoute
  AuthenticatedNotasIndexRoute: typeof AuthenticatedNotasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDeseosRoute: AuthenticatedDeseosRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedDiversionRoute: AuthenticatedDiversionRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedNotasIdRoute: AuthenticatedNotasIdRoute,
  AuthenticatedNotasIndexRoute: AuthenticatedNotasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
